"""HTML report generator for OverflowGuard findings."""
from __future__ import annotations

from analyzer import Finding

_RISK_COLOR = {
    "CRITICAL": "#c0392b",
    "HIGH":     "#e67e22",
    "MEDIUM":   "#f1c40f",
    "LOW":      "#27ae60",
}

_RISK_BG = {
    "CRITICAL": "#fde8e8",
    "HIGH":     "#fef3e2",
    "MEDIUM":   "#fefce8",
    "LOW":      "#eafaf1",
}

def generate_html(filename: str, source: str, findings: list[Finding]) -> str:
    total = len(findings)
    counts = {r: sum(1 for f in findings if f.risk == r)
              for r in ("CRITICAL", "HIGH", "MEDIUM", "LOW")}

    rows = ""
    for f in findings:
        color  = _RISK_COLOR.get(f.risk, "#333")
        bg     = _RISK_BG.get(f.risk, "#fff")
        rows += f"""
        <tr style="background:{bg}">
          <td style="text-align:center;font-weight:bold">{f.line_number}</td>
          <td>{_esc(f.function_name)}</td>
          <td><code>{_esc(f.expression)}</code></td>
          <td><code>{_esc(f.line_content)}</code></td>
          <td style="color:{color};font-weight:bold;text-align:center">{f.risk}</td>
          <td style="text-align:center">{_esc(f.risk_type)}</td>
          <td style="text-align:center">{_esc(f.certainty_type)}</td>
          <td style="font-weight:bold;text-align:center">{f.confidence}</td>
          <td>{_esc(f.reason)}</td>
          <td style="font-family:monospace;font-size:0.85em">{_esc(f.suggestion)}</td>
        </tr>"""

    source_lines = ""
    line_set = {f.line_number for f in findings}
    risk_map  = {f.line_number: f.risk for f in findings}
    for i, line in enumerate(source.splitlines(), start=1):
        color = _RISK_COLOR.get(risk_map.get(i), "transparent")
        bg    = _RISK_BG.get(risk_map.get(i), "transparent")
        marker = f' style="background:{bg};border-left:4px solid {color};padding-left:6px"' if i in line_set else ""
        source_lines += f'<span{marker}>{i:4d}  {_esc(line)}\n</span>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>OverflowGuard Report — {_esc(filename)}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          margin: 0; background: #f4f6f9; color: #222; }}
  .wrap {{ max-width: 960px; margin: 40px auto; padding: 0 20px 60px; }}
  h1 {{ color: #1a1a2e; }}
  .badge {{ display:inline-block; padding:4px 12px; border-radius:20px;
            color:#fff; font-weight:bold; font-size:.85em; margin-right:6px; }}
  .stat-grid {{ display:flex; gap:16px; flex-wrap:wrap; margin:24px 0; }}
  .stat {{ background:#fff; border-radius:10px; padding:16px 24px;
           box-shadow:0 2px 8px rgba(0,0,0,.07); text-align:center; flex:1; }}
  .stat .num {{ font-size:2em; font-weight:bold; }}
  table {{ width:100%; border-collapse:collapse; background:#fff;
           border-radius:10px; overflow:hidden;
           box-shadow:0 2px 8px rgba(0,0,0,.07); }}
  th {{ background:#1a1a2e; color:#fff; padding:12px 14px; text-align:left; }}
  td {{ padding:10px 14px; border-bottom:1px solid #eee; vertical-align:top; }}
  pre {{ background:#1e1e2e; color:#cdd6f4; padding:20px; border-radius:10px;
         overflow-x:auto; font-size:.85em; line-height:1.6; white-space:pre; }}
  .footer {{ text-align:center; color:#999; font-size:.8em; margin-top:40px; }}
</style>
</head>
<body>
<div class="wrap">
  <h1>🔍 OverflowGuard — Analysis Report</h1>
  <p><strong>File:</strong> {_esc(filename)}</p>

  <div class="stat-grid">
    <div class="stat">
      <div class="num" style="color:#333">{total}</div>
      <div>Total Findings</div>
    </div>
    <div class="stat">
      <div class="num" style="color:{_RISK_COLOR['CRITICAL']}">{counts['CRITICAL']}</div>
      <div>Critical</div>
    </div>
    <div class="stat">
      <div class="num" style="color:{_RISK_COLOR['HIGH']}">{counts['HIGH']}</div>
      <div>High</div>
    </div>
    <div class="stat">
      <div class="num" style="color:{_RISK_COLOR['MEDIUM']}">{counts['MEDIUM']}</div>
      <div>Medium</div>
    </div>
    <div class="stat">
      <div class="num" style="color:{_RISK_COLOR['LOW']}">{counts['LOW']}</div>
      <div>Low</div>
    </div>
  </div>

  <h2>Findings</h2>
  <table>
    <thead>
      <tr>
        <th>Line</th><th>Function</th><th>Expression</th><th>Code</th>
        <th>Severity</th><th>Risk Type</th><th>Certainty</th><th>Confidence</th>
        <th>Reason</th><th>Suggested Fix</th>
      </tr>
    </thead>
    <tbody>{rows if rows else '<tr><td colspan="10" style="text-align:center;padding:20px">No vulnerabilities found.</td></tr>'}</tbody>
  </table>

  <h2 style="margin-top:40px">Annotated Source</h2>
  <pre>{source_lines}</pre>

  <div class="footer">Generated by OverflowGuard · Static Integer Overflow Analyzer</div>
</div>
</body>
</html>"""


def _esc(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;"))
